### PR TITLE
Add har recorder

### PR DESCRIPTION
**Pull request by thypon**
Continues https://github.com/brave/pagegraph-crawl/pull/180

### CODE REVIEW

**Comment by FHantke** [comment]
@pes10k Can confirm, branch still works as expected.

**Comment by FHantke** [comment]
@pes10k I don't have the access rights to push here. Added tests to my fork https://github.com/FHantke/pagegraph-crawl/tree/add-har-recorder

**Comment by pes10k** [comment]
@diracdeltas these are just dev dependencies, and all pulled in from `standardjs`. Since they're just dev dependencies i was hoping they could be ignored.

If not, is there an alternative security recommends other than standardjs? IIRC it was either suggested or required for all code for a while. I can search for something kept more up to date, but if any suggestions greatly appreciated

**Comment by pes10k** [comment]
>> @diracdeltas these are just dev dependencies, and all pulled in from standardjs. Since they're just dev dependencies i was hoping they could be ignored.
>> 
>> If not, is there an alternative security recommends other than standardjs? IIRC it was either suggested or required for all code for a while. I can search for something kept more up to date, but if any suggestions greatly appreciated

> we do use standard in basically all js repos but i haven't seen these issues. they might be false positives then.

Hmm, odd, I don't think they're false positives. The current version of `standard` really does depend on the `[8.57.1](https://socket.dev/npm/package/eslint/overview/8.57.1)` `eslint` version socket.io is complaining about (see https://github.com/standard/standard/blob/master/package.json#L18 for example).

Are those other projects configured differently?  Would really like to not need to remove `standard` here (its very handy) if possible

**Review by pes10k — APPROVED** [review]
Looks good.  Discussing what to do with socket.io warnings in other channels

**Pull request merged**
